version: '3.7'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
      - "GF_AUTH_ANONYMOUS_HIDE_VERSION=true"
    volumes:
      # Mount provisioning configuration
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      # Mount dashboards
      - "../grafana-dashboards:/var/lib/grafana/dashboards"
    ports: 
      - 3000:3000

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # Mount prometheus configuration
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports: 
      - 9090:9090
