{
 "title": "Kafka Consumer Offsets",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(vectorized_kafka_group_offset{topic !~ 'controller|group|__consumer_offsets'}, group)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(vectorized_cluster_partition_end_offset{topic !~ 'controller|group|__consumer_offsets'}, topic)"
    }
   },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "Topic : topic,Topic\\,Partition : topic\\,partition"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Consumer Group Offset Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((vectorized_cluster_partition_end_offset{topic=~\"[[topic]]\"}) - on(instance, topic, partition) (vectorized_kafka_group_offset{topic=~\"[[topic]]\", group=~\"[[group]]\"})) by ([[aggr_criteria]])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Group Offset Lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vectorized_cluster_partition_end_offset{topic=~\"[[topic]]\"} - on(instance, topic, partition) vectorized_kafka_group_offset{topic=~\"[[topic]]\", group=~\"[[group]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log End Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vectorized_cluster_partition_end_offset{topic=~\"[[topic]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "topic: {{topic}}, partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Last Stable Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vectorized_cluster_partition_committed_offset{topic=~\"[[topic]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "topic: {{topic}}, partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Topic Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vectorized_storage_log_partition_size{topic=~\"[[topic]]\"}) by ([[aggr_criteria]])",
     "legendFormat": "topic: {{topic}}, partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Offsets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((vectorized_kafka_group_offset{topic=~\"[[topic]]\"})) by ([[aggr_criteria]], group) ",
     "legendFormat": "group: {{group}}, topic: {{topic}}, partition: {{partition}}"
    }
   ]
  }
 ]
}