{
 "title": "Kafka Consumer Offsets",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "redpanda_group",
    "label": "Group",
    "query": {
     "query": "label_values(redpanda_kafka_consumer_group_topics{redpanda_topic !~ 'controller|group|__consumer_offsets'}, redpanda_group)"
    }
   },
   {
    "name": "redpanda_topic",
    "label": "Topic",
    "query": {
     "query": "label_values(redpanda_kafka_replicas{redpanda_topic !~ 'controller|group|__consumer_offsets', redpanda_namespace=\"kafka\"}, redpanda_topic)"
    }
   },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "Topic : redpanda_topic,Topic\\,Partition : redpanda_topic\\,redpanda_partition"
   },
   {
    "name": "data_cluster",
    "label": "Data cluster",
    "query": {
     "query": "label_values(redpanda_cloud_data_cluster_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Consumer Group Offset Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by([[aggr_criteria]] , redpanda_group) (max by(redpanda_namespace, redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{redpanda_group=~\"[[redpanda_group]]\"}) +1)",
     "legendFormat": "Group: {{redpanda_group}}, Topic: {{redpanda_topic}}, Partition: {{redpanda_partition}}"
    }
   ]
  },
  {
   "title": "Consumer Groups",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(redpanda_group)(redpanda_kafka_consumer_group_committed_offset{redpanda_topic=~\"[[redpanda_topic]]\", redpanda_group=~\"[[redpanda_group]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}))"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(redpanda_kafka_max_offset{redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) by (redpanda_topic, redpanda_partition))",
     "legendFormat": "group: {{group}}, redpanda_topic: {{redpanda_topic}}, partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Offset Lag",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by(redpanda_namespace, redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{redpanda_group=~\"[[redpanda_group]]\", redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}) + 1)",
     "legendFormat": "group: {{group}}, redpanda_topic: {{redpanda_topic}}, partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Offset Lag (time)",
   "type": "stat",
   "description": "Only applies when topics are being written to (to understand the write-rate and compute the offset against that)",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg\n(\n    (max by(redpanda_namespace, redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\", redpanda_topic!=\"__consumer_offsets\"}) - on (redpanda_topic, redpanda_partition) group_right max by(redpanda_group,redpanda_topic, redpanda_partition) (redpanda_kafka_consumer_group_committed_offset{redpanda_group=~\"[[redpanda_group]]\",redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"})\n    )\n    / on (redpanda_topic, redpanda_partition) group_right\n    max by(redpanda_namespace, redpanda_topic, redpanda_partition) (rate(redpanda_kafka_max_offset{redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval])!=0) \n)",
     "legendFormat": "group: {{group}}, redpanda_topic: {{redpanda_topic}}, partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Offset Lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by([[aggr_criteria]] , redpanda_group) (max by(redpanda_namespace, redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{redpanda_group=~\"[[redpanda_group]]\"}) +1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Consumption Rate by Group",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "sum by(redpanda_group, redpanda_topic) (rate(redpanda_kafka_consumer_group_committed_offset{redpanda_topic=~\"[[redpanda_topic]]\", redpanda_group=~\"[[redpanda_group]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[1m]))",
     "legendFormat": "Group: {{redpanda_group}}"
    }
   ]
  },
  {
   "title": "Topic Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "sum by([[aggr_criteria]] ) (rate(redpanda_kafka_max_offset{redpanda_topic=~\"[[redpanda_topic]]\",redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval]))",
     "legendFormat": "Topic: {{redpanda_topic}}, Partition: {{redpanda_partition}}"
    }
   ]
  },
  {
   "title": "Topic Consumption Rate by Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "expr": "sum by([[aggr_criteria]], redpanda_group ) (rate(redpanda_kafka_consumer_group_committed_offset{redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval]))",
     "legendFormat": "group: {{redpanda_group}}, topic: {{redpanda_topic}}, partition: {{redpanda_partition}}"
    }
   ]
  },
  {
   "title": "Log End Offset Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by([[aggr_criteria]]) (rate(redpanda_kafka_max_offset{redpanda_topic=~\"[[redpanda_topic]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval]))",
     "legendFormat": "Topic: {{redpanda_topic}}, Partition: {{redpanda_partition}}"
    }
   ]
  },
  {
   "title": "Consumer Group Offsets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by([[aggr_criteria]], redpanda_group) (rate(redpanda_kafka_consumer_group_committed_offset{redpanda_topic=~\"[[redpanda_topic]]\", redpanda_group=~\"[[redpanda_group]]\", redpanda_cloud_data_cluster_name=~\"[[data_cluster]]\"}[$__rate_interval]))",
     "legendFormat": "Group: {{redpanda_group}}, Topic: {{redpanda_topic}}, Partition: {{redpanda_partition}}"
    }
   ]
  }
 ]
}