{
 "title": "Wasm",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(function_name) (redpanda_transform_lag)",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Egress Thoughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(function_name) (rate(redpanda_transform_write_bytes[$__rate_interval]))",
     "legendFormat": "write-{{function_name}}"
    }
   ]
  },
  {
   "title": "Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, function_name) (rate(redpanda_transform_execution_latency_sec_bucket[$__rate_interval])))",
     "legendFormat": "P99 {{function_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, function_name) (rate(redpanda_transform_execution_latency_sec_bucket[$__rate_interval])))",
     "legendFormat": "P95 {{function_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, function_name) (rate(redpanda_transform_execution_latency_sec_bucket[$__rate_interval])))",
     "legendFormat": "P50 {{function_name}}"
    }
   ]
  },
  {
   "title": "Ingress Thoughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(function_name) (rate(redpanda_transform_read_bytes[$__rate_interval]))",
     "legendFormat": "read-{{function_name}}"
    }
   ]
  },
  {
   "title": "Transforms Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(function_name, state) (redpanda_transform_state) > 0 ",
     "legendFormat": "{{state}}-{{function_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(function_name) (redpanda_wasm_engine_memory_usage)  ",
     "legendFormat": "Usage-{{function_name}}"
    },
    {
     "expr": "sum by(function_name) (redpanda_wasm_engine_max_memory)",
     "legendFormat": "Max-{{function_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(function_name) (rate(redpanda_wasm_engine_cpu_seconds_total[$__rate_interval])) > 0 ",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Records Transformed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(function_name) (rate(redpanda_transform_execution_latency_sec_count[$__rate_interval])) ",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Transform Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(function_name) (rate(redpanda_transform_failures[$__rate_interval])) > 0 ",
     "legendFormat": "Failures-{{function_name}}"
    }
   ]
  },
  {
   "title": "Executable Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(redpanda_wasm_binary_executable_memory_usage)  ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}