{
 "title": "Redpanda Migrator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Input Migrator Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "redpanda_migrator_input_redpanda_migrator_lag",
     "legendFormat": "{{topic}} partition: {{partition}}"
    }
   ]
  },
  {
   "title": "Input Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "redpanda_migrator_input_received",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99 Input Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "redpanda_migrator_input_latency_ns{quantile=\"0.9\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Processor Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "redpanda_migrator_processor_sent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(redpanda_migrator_output_error[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "redpanda_migrator_output_sent", "legendFormat": "__auto" }
   ]
  }
 ]
}