{
 "title": "Redpanda",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "label_values(instance)" },
   { "name": "node_shard", "label": "Shard", "query": "label_values(shard)" },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "Cluster : cluster,Instance : instance,Instance\\,Shard : instance\\,shard"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Summary</h1>"
  },
  {
   "title": "Nodes Up",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "redpanda_cluster_brokers", "legendFormat": "Nodes Up" }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "redpanda_cluster_partitions", "legendFormat": "Partition count" }
   ]
  },
  {
   "title": "Latency of Kafka consume requests (p95) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"consume\"}[$__rate_interval])) by (le, provider, region, instance, namespace, pod))",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  {
   "title": "Latency of Kafka produce requests (p95) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"produce\"}[$__rate_interval])) by (le, provider, region, instance, namespace, pod))",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  {
   "title": "Latency of Kafka consume requests (p99) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"consume\"}[$__rate_interval])) by (le, provider, region, instance, namespace, pod))",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  {
   "title": "Latency of Kafka produce requests (p99) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"produce\"}[$__rate_interval])) by (le, provider, region, instance, namespace, pod))",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Internal RPC Latency</h1>"
  },
  {
   "title": "RPC latency (p95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_rpc_request_latency_seconds_bucket{instance=~\"$node\",redpanda_server=\"internal\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  {
   "title": "RPC latency (p99)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_rpc_request_latency_seconds_bucket{instance=~\"$node\",redpanda_server=\"internal\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "node: {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Throughput</h1>"
  },
  {
   "title": "Throughput of Kafka produce/consume requests for the cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total[$__rate_interval])) by (redpanda_request)",
     "legendFormat": "redpanda_request: {{redpanda_request}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Total number of rest_proxy server errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_rest_proxy_request_errors_total{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_status: {{redpanda_status}}"
      }
     ]
    },
    {
     "title": "Rate - Number of rpc errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_rpc_request_errors_total{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_server: {{redpanda_server}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of schema_registry server errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_schema_registry_request_errors_total{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_status: {{redpanda_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "io_queue",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Total read operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_io_queue_total_read_ops{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total write operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_io_queue_total_write_ops{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_allocated_memory{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Total shard memory potentially available in bytes (free_memory plus reclaimable)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_available_memory{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "The low-water mark for available_memory from process start",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_available_memory_low_water_mark{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Free memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_free_memory{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "others",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redpanda build information",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_application_build{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_revision: {{redpanda_revision}}, redpanda_version: {{redpanda_version}}"
      }
     ]
    },
    {
     "title": "Redpanda uptime in seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_application_uptime_seconds_total{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of configured brokers in the cluster",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_brokers{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Controller log rate limiting. Available rps for group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_controller_log_limit_requests_available_rps{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_cmd_group: {{redpanda_cmd_group}}"
      }
     ]
    },
    {
     "title": "Rate - Controller log rate limiting. Amount of requests that are dropped due to exceeding limit in group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_cluster_controller_log_limit_requests_dropped{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_cmd_group: {{redpanda_cmd_group}}"
      }
     ]
    },
    {
     "title": "Amount of partitions that are moving from node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partition_moving_from_node{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Amount of partitions that are moving to node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partition_moving_to_node{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Amount of cancelling partition movements for node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partition_node_cancelling_movements{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of partitions in the cluster (replicas not included)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partitions{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of topics in the cluster",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_topics{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of partitions that lack quorum among replicants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_unavailable_partitions{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Total CPU busy time in seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cpu_busy_seconds_total{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Latest committed offset for the partition (i.e. the offset of the last message safely persisted on most replicas)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_max_offset{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_partition: {{redpanda_partition}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Configured number of partitions for the topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_partitions{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Configured number of replicas for the topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_replicas{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of bytes produced per topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_kafka_request_bytes_total{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_request: {{redpanda_request}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Internal latency of kafka produce requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_request_latency_seconds{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_request: {{redpanda_request}}"
      }
     ]
    },
    {
     "title": "Number of under replicated replicas (i.e. replicas that are live, but not at the latest offest)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_under_replicated_replicas{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_partition: {{redpanda_partition}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Number of node status RPCs received by this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_node_status_rpcs_received{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of node status RPCs sent by this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_node_status_rpcs_sent{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of timed out node status RPCs from this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_node_status_rpcs_timed_out{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Internal latency of request for rest_proxy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_rest_proxy_request_latency_seconds{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Count of currently active connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_rpc_active_connections{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_server: {{redpanda_server}}"
      }
     ]
    },
    {
     "title": "RPC latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_rpc_request_latency_seconds{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_server: {{redpanda_server}}"
      }
     ]
    },
    {
     "title": "Internal latency of request for schema_registry",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_schema_registry_request_latency_seconds{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "raft",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Number of leadership changes across all partitions of a given topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_raft_leadership_changes{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Bandwidth available for partition movement. bytes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_raft_recovery_partition_movement_available_bandwidth{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Accumulated runtime of task queue associated with this scheduling group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_scheduler_runtime_seconds_total{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, redpanda_scheduling_group: {{redpanda_scheduling_group}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "storage",
   "type": "row",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk storage bytes free.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_storage_disk_free_bytes{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Status of low storage space alert. 0-OK, 1-Low Space 2-Degraded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_storage_disk_free_space_alert{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Total size of attached storage, in bytes.",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_storage_disk_total_bytes{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}