{
 "title": "Redpanda Serverless Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "data_cluster",
    "label": "Data cluster",
    "query": "label_values(redpanda_cloud_data_cluster_name)"
   }
  ]
 },
 "panels": [
  { "title": "Redpanda Serverless Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Serverless Overview</h1>"
   }
  },
  {
   "title": "Redpanda Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, last_over_time(redpanda_application_build{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "Data transferred from the clients to the Serverless Cluster (Ingress) and from the Serverless Cluster to the clients (Egress)",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (listener) (rate(redpanda_serverless_ingress_bytes_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Ingress ({{listener}})"
    },
    {
     "expr": "sum by (listener) (rate(redpanda_serverless_egress_bytes_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Egress ({{listener}})"
    }
   ]
  },
  {
   "title": "Records",
   "type": "timeseries",
   "description": "Number of records produced or fetched from the Serverless Cluster",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_records_produced_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Produced"
    },
    {
     "expr": "sum(rate(redpanda_kafka_records_fetched_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Fetched"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redpanda_cluster_topics{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Topics count"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redpanda_cluster_partitions{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Consumers per Group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(redpanda_kafka_consumer_group_consumers{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) by (redpanda_group)",
     "legendFormat": "{{redpanda_consumer_group}}"
    }
   ]
  },
  {
   "title": "Lag Sum per Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redpanda_kafka_consumer_group_lag_sum{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) by (redpanda_group)",
     "legendFormat": "{{redpanda_group}}"
    }
   ]
  },
  {
   "title": "Most active topics",
   "type": "barchart",
   "description": "Total produce and fetch activities",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(6, sum by (redpanda_topic) (\n  rate(redpanda_kafka_records_produced_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]) + \n  rate(redpanda_kafka_records_fetched_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval])\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (listener) (redpanda_serverless_connections_active{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Active Connections ({{listener}})"
    }
   ]
  },
  {
   "title": "New Connections Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (listener) (rate(redpanda_serverless_connections_created_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "New Connections Rate ({{listener}})"
    }
   ]
  },
  {
   "title": "Avg Connection Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (listener)(rate(redpanda_serverless_connections_duration_seconds_sum{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval])) / sum by (listener)(rate(redpanda_serverless_connections_duration_seconds_count{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Avg Duration ({{listener}})"
    }
   ]
  },
  { "title": "Resource Quota (Soft Limits)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Resource Quota (Soft Limits)</h1>"
   }
  },
  {
   "title": "Partition Quota",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(redpanda_cluster_partitions{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) / sum(redpanda_serverless_resource_limit{resource=\"partitions\", redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})) * 100",
     "legendFormat": "Partition Usage"
    }
   ]
  },
  {
   "title": "Topic Quota",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (redpanda_cluster_topics{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) / sum(redpanda_serverless_resource_limit{resource=\"topics\", redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})) * 100",
     "legendFormat": "Partition Usage"
    }
   ]
  },
  {
   "title": "Ingress Quota",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate(redpanda_serverless_ingress_bytes_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[5m])) / sum (redpanda_serverless_resource_limit{resource=\"ingress\", redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})) * 100",
     "legendFormat": "Ingress Rate Usage"
    }
   ]
  },
  {
   "title": "Egress Quota",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate(redpanda_serverless_egress_bytes_total{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[5m])) / sum (redpanda_serverless_resource_limit{resource=\"egress\", redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})) * 100",
     "legendFormat": "Egress Rate Usage"
    }
   ]
  },
  {
   "title": "Connection Quota",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (redpanda_serverless_connections_active{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) / sum(redpanda_serverless_resource_limit{resource=\"connections\", redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})) * 100",
     "legendFormat": "Connection Limit"
    }
   ]
  },
  { "title": "Schema Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Schema Registry</h1>"
   }
  },
  {
   "title": "Schemas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redpanda_schema_registry_cache_schema_count{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Total Schemas"
    }
   ]
  },
  {
   "title": "Schema Registry Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (listener) (rate(redpanda_schema_registry_request_latency_seconds_count{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Request Rate ({{listener}})"
    }
   ]
  },
  {
   "title": "Schema Registry P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, listener) (rate(redpanda_schema_registry_request_latency_seconds_bucket{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))) * 1000",
     "legendFormat": "P95 Latency ({{listener}})"
    }
   ]
  },
  {
   "title": "Schema Registry Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "errps" } },
   "targets": [
    {
     "expr": "sum(rate(redpanda_schema_registry_request_errors{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "Error Rate"
    }
   ]
  },
  { "title": "Redpanda Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Connect</h1>"
   }
  },
  {
   "title": "Running Pipelines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (pipeline_id) (input_connection_up{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}))",
     "legendFormat": "Running Pipelines"
    }
   ]
  },
  {
   "title": "Input Throughput",
   "type": "timeseries",
   "description": "Message rate for data flowing into Redpanda Connect pipelines",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (pipeline_id) (rate(input_received{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "{{pipeline_id}}"
    }
   ]
  },
  {
   "title": "Output Throughput",
   "type": "timeseries",
   "description": "Message rate for data flowing out of Redpanda Connect pipelines",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "sum by (pipeline_id) (rate(output_sent{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))",
     "legendFormat": "{{pipeline_id}}"
    }
   ]
  },
  {
   "title": "Input Connections Down",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(input_connection_failed{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) OR sum(input_connection_lost{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Total Input Down"
    }
   ]
  },
  {
   "title": "Output Connections Down",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(output_connection_failed{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}) OR sum(output_connection_lost{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Total Output Down"
    }
   ]
  },
  {
   "title": "Processor Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(processor_error{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Total Processor Error"
    }
   ]
  },
  {
   "title": "Output Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(output_error{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"})",
     "legendFormat": "Total Output Errors"
    }
   ]
  },
  {
   "title": "Input P90 Latency (ms)",
   "type": "timeseries",
   "description": "P95 latency for messages traveling through the connector input stages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pipeline_id) (input_latency_ns{redpanda_cloud_data_cluster_name=~\"${data_cluster}\", quantile=\"0.9\"}) / 1000000",
     "legendFormat": "{{pipeline_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(output_latency_ns_bucket{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))) / 1000000",
     "legendFormat": "Output P95 Latency"
    }
   ]
  },
  {
   "title": "Output P90 Latency (ms)",
   "type": "timeseries",
   "description": "P95 latency for messages traveling through the connector output stages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (pipeline_id) (output_latency_ns{redpanda_cloud_data_cluster_name=~\"${data_cluster}\", quantile=\"0.9\"}) / 1000000",
     "legendFormat": "{{pipeline_id}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(output_latency_ns_bucket{redpanda_cloud_data_cluster_name=~\"${data_cluster}\"}[$__rate_interval]))) / 1000000",
     "legendFormat": "Output P95 Latency"
    }
   ]
  }
 ]
}