global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'redpanda'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - <REDACTED>
    metrics_path: /api/cloud/prometheus/public_metrics
    basic_auth:
      username: prometheus
      password: <REDACTED>
    scheme: https
