version: '3.7'
services:
  connect:
    image: cnfldemos/cp-server-connect-datagen:0.5.0-6.2.0
    hostname: connect
    container_name: connect
    depends_on:
      - redpanda0
      - redpanda1
      - redpanda2
    ports:
      - "8085:8085"
      - "9010:9010"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'redpanda-0:29092,redpanda-1:29093,redpanda-2:29093'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8085
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://redpanda-0:8081
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      KAFKA_JMX_PORT: 9010
      CLASSPATH: "/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.14.0.jar"
      KAFKA_JMX_OPTS: "-javaagent:/usr/share/java/cp-base-new/jmx_prometheus_javaagent-0.14.0.jar=9090:/etc/kafka-connect/kafka.yml"
    volumes: [ "./config/jmx_exporter/kafka.yml:/etc/kafka-connect/kafka.yml" ]

  # OwlShop is a service that simulates an ecommerce shop that has producers and consumers. It will setup
  # a few Kafka topics, produces to them and also consumes the data again via consumer groups.
  owl-shop:
    #image: quay.io/cloudhut/owl-shop:v1.2.0
    image: quay.io/cloudhut/owl-shop:latest
    environment:
      - SHOP_KAFKA_BROKERS=redpanda-0:29092,redpanda-1:29093,redpanda-2:29093
      - SHOP_KAFKA_TOPICREPLICATIONFACTOR=1
      - SHOP_TRAFFIC_INTERVAL_RATE=1
      - SHOP_TRAFFIC_INTERVAL_DURATION=0.1s
    depends_on:
      - redpanda0
      - redpanda1
      - redpanda2