global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: redpanda
  static_configs:
  - targets:
    - redpanda-0:9644
    - redpanda-1:9644
    - redpanda-2:9644
  metrics_path: /public_metrics
- job_name: connect
  static_configs:
  - targets:
    - connect:9010
  metrics_path: /
